### ISSUE TITLE
The footer is in the wrong position

### ISSUE THREAD

**Issue by pierreneter** [opencollective/frontend#276] opened 2018-03-07 01:25 UTC
On any page except the home page, like: project, profile, etc,...

![footer](https://user-images.githubusercontent.com/12815768/37068316-a0a2b2a0-21e0-11e8-910b-1e48508162b6.png)

URLs for error reference:
https://opencollective.com/webpack
https://opencollective.com/tobiaskoppers

**Comment by pierreneter** [comment] 2018-03-07 16:07
I think it's a mistake at Footer components: https://github.com/opencollective/frontend/blob/master/src/components/Footer.js#L15
position absolute and bottom 0 make it be stick on the first screen.

**Comment by piamancini** [comment] 2018-03-07 16:13
hmm I can't reproduce it myself and every time I saw it was due to plugins. 
Is this happening for you in different browsers and/or incognito as well?

**Comment by pierreneter** [comment] 2018-03-07 16:23
oh, It gone in incognito browser, I'm trying test with my per extensions.

**Comment by pierreneter** [comment] 2018-03-07 16:37
This's https://chrome.google.com/webstore/detail/free-proxy-to-unblock-any/bihmplhobchoageeokmgbdihknkjbknd?utm_source=chrome-app-launcher-info-dialog

It add a prepend `div` inside `body`. It make footer work wrong.

Normal:
![normal](https://user-images.githubusercontent.com/12815768/37104910-75e3243e-2260-11e8-8528-eb6a60ce9f3c.png)

With this ext:
![with-the-ex](https://user-images.githubusercontent.com/12815768/37104921-7a24fa2c-2260-11e8-88a2-248d94cd9755.png)

**Comment by piamancini** [comment] 2018-03-07 16:44
thanks @pierreneter we'll look into this. 
cc/ @xdamman

**Comment by znarf** [comment] 2018-04-19 09:39
Closing.

**Closed by znarf** 2018-04-19 09:39 UTC
